### ISSUE TITLE
Reports --> Subscriptions

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#503]
Hi!
Just upgraded to the latest v2020.05.0 version and having two strange issues in reports section.
Testing new features, but by pressing on Subscriptions i get:
```
<type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'quantize'
```

**Comment by edwinvandeven** [comment]
Hi,
I don't seem to be able to reproduce the issue. What version of python are your running? Are the python modules the same version as in requirements.txt?
It should work on python 3.6 ~ 3.8 with the modules from requirements.txt in the OpenStudio root directory.

**Comment by mgailitis** [comment]
Investigated this issue! During upgrade process sql lost Prices column in Subscriptions table. Created it by hand and had to recover values there. Right now it works.
